---
# tasks file for frontend
- name: Install frontend dependencies
  become: yes
  npm:
    path: /opt/todo-app/todo-frontend
    state: present

- name: Run frontend build
  become: yes
  args:
    chdir: /opt/todo-app/todo-frontend
  command: npm run build
