# ---
# # tasks file for backend

# - name: Install dependencies from package.json
#   become: yes
#   npm:
#     path: /opt/todo-app/todo-backend
#     state: present

# - name: Install dotenv Node.js module
#   become: yes
#   npm:
#     name: dotenv
#     path: /opt/todo-app/todo-backend
#     state: present

# - name: Install PM2 globally
#   become: yes
#   npm:
#     name: pm2
#     global: yes

# - name: Check if start.js exists
#   stat:
#     path: /opt/todo-app/todo-backend/start.js
#   register: start_js

# - name: Debug start.js existence
#   debug:
#     msg: "start.js exists? {{ start_js.stat.exists }}"

# - name: Create PM2 ecosystem.config.js
#   become: yes
#   copy:
#     dest: /opt/todo-app/todo-backend/ecosystem.config.js
#     content: |
#       module.exports = {
#         apps: [{
#           name: "todo-backend",
#           script: "start.js",
#           cwd: "/opt/todo-app/todo-backend",
#           env: {
#             NODE_ENV: "production",
#             PORT: 3002
#           }
#         }]
#       };
#     mode: '0644'
#   when: start_js.stat.exists

# - name: Start backend using PM2 ecosystem config
#   become: yes
#   command: pm2 start ecosystem.config.js
#   args:
#     chdir: /opt/todo-app/todo-backend
#   when: start_js.stat.exists

# - name: Set PM2 to start on boot
#   become: yes
#   command: pm2 startup
#   args:
#     chdir:



---
# tasks file for backend
- name: Install dependencies on todo-backend from package.json
  become: yes
  npm:
     path: /opt/todo-app/todo-backend
     state: present

- name: Install dotenv Node.js module
  become: yes
  npm:
    name: dotenv
    path: /opt/todo-app/todo-backend
    state: present


- name: Install PM2 globally
  become: yes
  npm: 
     name: pm2
     global: yes

- name: check if start.js is present or not
  stat:
    path: /opt/todo-app/todo-backend/start.js
  register: start_js

- name: Debugging start.js existence
  debug:
    msg: "Start.js status: {{start_js.stat.exists}}"

- name: Check the PM2 list
  become: yes
  command: pm2 list
  register: pm2_list
  changed_when: false

- name: Debug the Pm2 list
  debug: 
    var: pm2_list
    
# - name: Start or restart the backend with pm2 and dotenv
#   become: yes
#   command : "pm2 start -f start.js --env production"
#   args:
#     chdir: /opt/todo-app/todo-backend
#   when: start_js.stat.exists

- name: Start or restart the backend with pm2
  become: yes
  command : "pm2 start -f start.js"
  args:
    chdir: /opt/todo-app/todo-backend
  when: start_js.stat.exists

- name: Set pm2 to start on boot
  become: yes
  command: pm2 startup
  args:
    chdir: /opt/todo-app/todo-backend
