name: provisioning of ec2 and configuring with ansible
on:
    push:
        branches:
            - main

jobs:
    provision_ec2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Setup python 3.x
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Instal dependencies
              run: |
                python -m pip install --upgrade pip
                pip install ansible boto3
                ansible-galaxy collection install amazon.aws
                